### ISSUE TITLE
Filter: initial version

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-MultiL#1]
Create an initial version of the Serverless /filter function

**Comment by susanodd** [comment]
The following error occurs when doing an ajax call to retrieve:

`Cross-Origin-aanvraag geblokkeerd: de Same Origin Policy staat het lezen van de externe bron op https://rkxy8021l6.execute-api.eu-central-1.amazonaws.com/Prod/list/ niet toe. (Reden: CORS-aanvraag is niet gelukt).`

**Comment by ErwinKomen** [comment]
Okay, I think I enabled it now.
What I did (for my own record):
1. Go to he AWS API gateway console https://console.aws.amazon.com/apigateway/home
2. Select the `sam-multil` stack
3. Go to each of the functions' `GET` method
4. Under `Actions` select `enable CORS`

**Comment by susanodd** [comment]
It's still giving the same error as above.

**Comment by ErwinKomen** [comment]
Not sure what you're doing...
I tested it with `curl`: no problem (without any additional parameters)
I tested a GET request using the program Postman: no problem

I have not tested it from Javascript yet... Let me do that...

**Comment by ErwinKomen** [comment]
Okay, I've now resolved it. It was a matter of adding the right RETURN statement:

``` python
    return {
        "statusCode": 200,
        'headers': {
            'Access-Control-Allow-Headers': 'Content-Type',
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'OPTIONS,POST,GET'
        },
        "body": json.dumps(body)
        }
```

**Comment by susanodd** [comment]
No, it still gives the error:
`CORS-header ‘Access-Control-Allow-Origin’ ontbreekt`

**Comment by susanodd** [comment]
What about duplicates in the Short Cite column?
Is the "unique identifier" the Short Cite rather than the Observation ?
It looks confusing to select Observations from a list because Short Cite is identical for multiple Observation IDs. The user would need to know the ID in order to disambiguate.

**Comment by ErwinKomen** [comment]
> What about duplicates in the Short Cite column?
> Is the "unique identifier" the Short Cite rather than the Observation ?
> It looks confusing to select Observations from a list because Short Cite is identical for multiple Observation IDs. > The user would need to know the ID in order to disambiguate.

@susanodd , could you turn this into a separate issue?
It seems to be unrelated to the creation of the serverless `/feature` issue?
Or am I missing something?

**Comment by susanodd** [comment]
What about quite large jqplot js files fetched into the client side html file via cdn.jsdelivr.net ?

**Comment by ErwinKomen** [comment]
> What about quite large jqplot js files fetched into the client side html file via cdn.jsdelivr.net ?

Please turn into separate issue
