### ISSUE TITLE
Back-end: allow creating, updating and deleting of new observations

### ISSUE THREAD

**Issue by Woseseltops** [ErwinKomen/RU-MultiL#12]
Involves updating the JSON file on S3

**Comment by ErwinKomen** [comment]
This involves creating a few new Python endpoints:
1. `/add` - add a (JSON) list of data to the existing data in S3.
    1. Note: if `/add` is called with JSON data where the `observation` id already exists, that data is overwritten
1. `/delete` - remove an item from the list of data in S3
    1. This could mean one of two things:
        1. Either physically remove the data row with the given `observation` id
        2. Or: set a field like `valid` to `false` for the given `observation` id

**Comment by susanodd** [comment]
Exporting the dataset to csv is now complete.

**Comment by ErwinKomen** [comment]
### Implementation of `/add`

1. Calling `/add` should be done with a JSON data object (dict) like: `{ "data": {"key": "value", "key2":, "value2", ...}}`

**Comment by susanodd** [comment]
How are we treating numerical versus text data?
On data entry I have select choices set up for the fields that are choices.
Some of the fields are numerical. Is this checked on the value/key pairs?

**Comment by susanodd** [comment]
How does the user acquire a new observation ID that is unique from all the other observations?
Is it merely distinguished between having an ID in the data and not having an ID in the data for the /add command?

**Comment by susanodd** [comment]
Do we allow '?' as a valid data? This appears in the Excel file. At the moment, this is not shown in the filters on observations. It is visible if the user has not filtered on a field. On some of the numerical fields, there are actually text like MD.

**Comment by ErwinKomen** [comment]
> How are we treating numerical versus text data? On data entry I have select choices set up for the fields that are choices. Some of the fields are numerical. Is this checked on the value/key pairs? It makes a difference because in the Excel file some fields have 0 and others are just blank.

Good point. Right now the `/add` code doesn't look for this. It's string / decimal / float / boolean that are possible values, depending on the field, I think. It would be easy enough to check this at the server-side. @Woseseltops , what do you think?

**Comment by ErwinKomen** [comment]
> How does the user acquire a new observation ID that is unique from all the other observations? Is it merely distinguished between having an ID in the data and not having an ID in the data for the /add command?

There is no real fail-safe way right now, since we are working just with S3 storage. 
So the way it works right now is:
1. Download all data using `/list`
2. Check what the largest `observation` id is within the dataset
3. Create your own new `observation` id by adding one to the largest from step (2)

And note that `observation` is an obligatory numerical (decimal) field for each data record.

I know this system is not fail safe at all. It basically assumes only one person is at any time editing the data. That's why I at least added the `edit_key`. 
@Woseseltops : how likely is it that more than one person will be _editing_ (i.e. adding to the dataset or changing items in it) at the same time?

**Comment by ErwinKomen** [comment]
> Do we allow '?' as a valid data? This appears in the Excel file. At the moment, this is not shown in the filters on observations. It is visible if the user has not filtered on a field. On some of the numerical fields, there are actually text like MD.

I think that the R-code handles the current dataset quite well, given these peculiarities. So I guess that we shouldn't bother about it right now.

**Comment by ErwinKomen** [comment]
Added a `/delete` option that is working (at least under `curl`).
The expected input is:
``` python
{ "edit_key": "SECRET",
  "observations": [300]
}
```

The output could be something of this form, depending on any errors encountered:
``` python
{"status": "ok", "data": [
   {"msg": "Observation ids [300] are in rows [187]"}, 
   {"msg": "There are 1 observations to be deleted"}, 
   {"msg": "Deleting observation id 300 at row 187"}, 
   {"msg": "Replacing the Dataset with the emended one"}, 
   {"msg": "The updated dataset has been put back to S3"}]}
```

**Comment by ErwinKomen** [comment]
Here is a Javascript/jQuery example of usage (partial code):

``` Javascript
      /**
       * multil_check
       *    Verify multil functionality
       */
      multil_check: function (elStart) {
        var url_base = "https://{aws}.execute-api.eu-central-1.amazonaws.com/Prod/{mode}",
            elMultilCheck = "",
            sAwsList = "rkxy8021l6",
            sAwsForest = "34kb2ospsg",
            bCheckForest = false,
            multil_row = null,
            multil_obs = null,
            url_list = "",
            url_add = "",
            url_delete = "",
            url_forest = "";

        try {
          // Create the URLs
          url_list = url_base.replace("{aws}", sAwsList).replace("{mode}", "list");
          url_add = url_base.replace("{aws}", sAwsList).replace("{mode}", "add");
          url_delete = url_base.replace("{aws}", sAwsList).replace("{mode}", "delete");
          url_forest = url_base.replace("{aws}", sAwsForest).replace("{mode}", "rforest");

          multil_row = loc_multil_row;
          multil_obs = multil_row['observation'];

          // Before we start
          elMultilCheck = $(elStart).closest(".multil-main").find(".multil-check").first();
          $(elMultilCheck).html(loc_sWaiting);

          // Test getting a list
          $.get(url_list, function (response) {
            var data = null,
                html = [],
                features = null,
                dataset = null;

            // Action depends on the response
            if (response === undefined || response === null || !("status" in response)) {
              private_methods.errMsg("No status returned");
            } else {
              switch (response.status) {
                case "ready":
                case "ok":
                  // Get the data
                  data = response.data;
                  features = data.Features;
                  dataset = data.Dataset;

                  // Compose a message
                  html.push("<p>Results from /list:</p>");
                  html.push("<table>");
                  html.push("<tr><td>Features:</td><td>" + features.length + "</td></tr>");
                  html.push("<tr><td>Dataset:</td><td>" + dataset.length + "</td></tr>");
                  html.push("</table>");

                  // SHow the message
                  $(elMultilCheck).html(html.join("\n"));

                  // Now call the /add method
                  data = JSON.stringify( {
                    edit_key: "KEY TO BE FILLED IN",
                    data: [ multil_row ]
                  });

                  $.post(url_add, data, function (post_add) {
                    var verder = null;

                    // Action depends on the response
                    if (post_add === undefined || post_add === null || !("status" in post_add)) {
                      private_methods.errMsg("No status returned");
                    } else {
                      switch (post_add.status) {
                        case "ready":
                        case "ok":
                          verder = post_add;

                          // Now calling the /delete method
                          data = JSON.stringify({
                            edit_key: "KEY TO BE FILLED IN",
                            observations: [multil_obs]
                          });
                          $.post(url_delete, data, function (post_delete) {
                            var verder = null;

                            // Action depends on the response
                            if (post_delete === undefined || post_delete === null || !("status" in post_delete)) {
                              private_methods.errMsg("No status returned");
                            } else {
                              switch (post_delete.status) {
                                case "ready":
                                case "ok":
                                  verder = post_delete;
                                  break;
                              }
                            }
                          });

                          break;
                      }
                    }
                  });

                  if (bCheckForest) {
                    // Now call the /rforest method
                    data = { calling: "usedatafilter", dataset: dataset };
                    $.post(url_forest, data, function (post_response) {
                      var verder = null;

                      // Action depends on the response
                      if (post_response === undefined || post_response === null || !("status" in post_response)) {
                        private_methods.errMsg("No status returned");
                      } else {
                        switch (post_response.status) {
                          case "ready":
                          case "ok":
                            verder = post_response;
                            break;
                        }
                      }
                    });
                  }

                  break;
              }
            }
          });

        } catch (ex) {
          private_methods.errMsg("multil_check", ex);
        }
      },

```

**Comment by ErwinKomen** [comment]
Working now!

**Comment by susanodd** [comment]
This probably needs to remain open. I've added the dynamically generated form code for entering the fields.
These now have explanations of what the data is.
It's checked that all fields are filled in. The ones that are choices, those are fine.
Other than that, I'm not sure what will happen if the user enters bogus data.
Considering that the forest plot data doesn't want certain values, as in the clean functionality, then I'm wondering which other form fields need to be strict before saving them?
For which fields is 0 a valid input (say as a default value)?

**Comment by susanodd** [comment]
Do we have a special parameter to indicate it's "unapproved" (possibly bogus) data?

**Comment by ErwinKomen** [comment]
> This probably needs to remain open. I've added the dynamically generated form code for entering the fields. These now have explanations of what the data is. It's checked that all fields are filled in. The ones that are choices, those are fine. Other than that, I'm not sure what will happen if the user enters bogus data. Considering that the forest plot data doesn't want certain values, as in the clean functionality, then I'm wondering which other form fields need to be strict before saving them? For which fields is 0 a valid input (say as a default value)?

Good thinking! But...
I think we would need to ask the researchers, instead of figuring this out ourselves. I would put this into **Phase 2**, if there ever comes a follow-up. Right now we've already given way more time to this than the first idea was.

**Comment by ErwinKomen** [comment]
> Do we have a special parameter to indicate it's "unapproved" (possibly bogus) data?

No, we don't, and it _is_ a bit bothering that I haven't figured out how to get it working properly, i.e. that the R-code simply ignores values it cannot handle.

What I _should_ do, probably, is emend the R-code:
1. It should evaluate all the data rows, and internally (in R) create a 'working' dataset based on
    1. either the incorrect measure of one of the fields in a data row
    2. or the existance of an `"unapproved": true` parameter in the datarow
1. Calculate forest plot based on the emended dataset
1. (Optionally: re-combine _all_ data, so that something is returned for each observation ???)
1. Return the results
