### ISSUE TITLE
Target 2023

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-MultiL#14]
### Data model changes
* `target_language`: choice > text
* `surface_overlap_author`: text > choice

### Additions to the data model
* text `email_address`
* bool `verified_by_administrators`
* text `task_detailed_other`
* text `linguistic_property_other`

**Comment by ErwinKomen** [comment]
### Implementation for the BACK END
1. `target_language`; this is used in multil_rcalc/assets/functions.R. It is assumed to have a text value (e.g. there is a test `target _language == "english"`). So the difference between `choice` (set of fixed values) and `text` (any [string] value) is irrelevant to the R-back end.
2. `surface_overlap_author`: the difference with `target_language` is that here we go from 'any [string] value' to a choice from a set of fixed values. No difference in processing for the R-back end (also used in `functions.R`)
3. Added fields to the data model:
    1. The fields are: `email_address` (string), `verified_by_administrators` (boolean), `task_detailed_other` (string), `linguistic_property_other` (string)
    2. The only change for the back-end is: provide an updated JSON that contains these fields

**Comment by Woseseltops** [comment]
Initial values:
* `email_address`: null
* `verified_by_administrators`: false
* `task_detailed_other`: probably null (but double check if this value is not in the original Excel)
* `linguistic_property_other`: same as above

**Comment by ErwinKomen** [comment]
Okay, the server-side of this is now adapted (there is an adapted JSON in place now)
