### ISSUE TITLE
Filter: remaining issues

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-MultiL#2]
This lists the remaining issues for the `/filter` capabilities of the serverless lambda.

### Issue list
1. Figure out whether POST access works / should work - _done_
1. Find out which specific columns (=features) should be included in possible filtering
1. Should the **dataset** be divided into sub-tables???
    1. Some columns (=features) have a limited number of values (e.g. 'language', 'task_type', ...)
    1. Put all possible (i.e: occurring) values in separate tables with an `id` for each entry
    1. The main dataset list should hold these columns with id values (i.e. foreign keys) rather than the actual values
    1. Add `/table` with parameter `name` (e.g. `/table?name=task_type`) to download the table that holds the different possible task types

**Comment by ErwinKomen** [comment]
As for (2): which columns should be filterable, WS wrote:

> Dan zijn de filteropties alvast helder: 
> 
> * target_language
> * task_type (5 opties)
> * task_detail (9 opties)
> * linguistic_property (7 opties)
> * surface_overlap_author (3 opties)
> * target_or_child_system (5 opties)
> * dominance (5 opties)
> * language_home (5 opties)
> * societal_language (5 opties)
> * mean_age_2L1: moet dan denk ik een soort slider worden?

**Comment by susanodd** [comment]
Here is what the first version of the interface looks like. This is based on a get of /Prod/list

I found it necessary to put an alert in for after all the data from the get has been processed. I put a timeout to force the code to wait. Getting the data isn't as face as displaying the page, so the data wasn't available.

I made two multiselect lists where the user selects the observations and the fields.
These are shown in a dynamically constructed table.
Here you see that it would be nice to have human readable field names in the table header.

The jquery, javascript and html are all in just the one file. I assume we assume that we can't have multiple files on the users computer?

![test_interface_ready](https://user-images.githubusercontent.com/24272544/178695057-526c8335-8b4e-47fc-8216-6e94fdb0cead.png)

![test_interface_multiselect_obs_fields](https://user-images.githubusercontent.com/24272544/178695097-4ec41774-44ba-47c0-b9d2-320b3ac81e66.png)

**Comment by ErwinKomen** [comment]
> We need human readable field names for the user interface. Or shall I just convert the underscore to space and make the words start with caps? (something that can be automated)

This is actually related to issue #5 , because that is where the whole list of 'features' that can be used (e.g. by the user in the interface) is available from, including a human-language description. Perhaps we should add a field with "display value" in there? 

Let's continue the discussion on this in issue #5

**Comment by susanodd** [comment]
I'll start out doing 1 since I'm trying to finish the interface. But ideally 2 would be better since the choices could also change over time and with filtering the entire set of observations, all possible choices might not be available among the downloaded batch.

**Comment by ErwinKomen** [comment]
Oh, but it's no big thing for me to do that server-side! That's just some Python code. 
Are you sure you want to do 1? I could do 2 this afternoon...

**Comment by susanodd** [comment]
1 is nearly done.
One weird thing, some of the entries have ? added to them. I'm removing those from the choices.

**Comment by susanodd** [comment]
And NA appears in several.

**Comment by susanodd** [comment]
Maybe some kind of "update" functionality would be of use on the server side?

**Comment by ErwinKomen** [comment]
> 1 is nearly done. One weird thing, some of the entries have ? added to them. I'm removing those from the choices.

Good idea!

**Comment by ErwinKomen** [comment]
> Maybe some kind of "update" functionality would be of use on the server side?

What would that need to do?

**Comment by susanodd** [comment]
Allow the users to correct typos in their data?

**Comment by ErwinKomen** [comment]
See issue #5: the `/feature` call now also makes available a field per feature called `values`.
This is a list of all the different values occurring in this particular feature in the dataset.

Note: these values are calculated **offline** from the Excel file that contains the source data.
So this functionality only works for data that is not modified online...
